SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[proc_BulkInsertEventData]
AS

--ALTER TABLE EventData NOCHECK CONSTRAINT ALL
INSERT INTO EventData SELECT * FROM EventDataTemp WHERE Archived = 0
--ALTER TABLE EventData CHECK CONSTRAINT ALL


GO
