SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[proc_ReportNCEByConfigId]
(
	@vids varchar(max),
	@dids varchar(max),
	@sdate datetime,
	@edate datetime,
	@uid UNIQUEIDENTIFIER,
	@rprtcfgid UNIQUEIDENTIFIER
)
AS

--DECLARE	@vids varchar(max),
--		@dids VARCHAR(MAX),
--		@sdate datetime,
--		@edate datetime,
--		@uid uniqueidentifier,
--		@rprtcfgid uniqueidentifier

--SET @vids = N'5AAB0E74-D39E-483B-AAFF-200FB5A56850,1860348D-20B5-42CF-BA66-203864BA0461,401CD56D-0E45-47C1-B982-37A277394749,BD5F9889-8007-4943-9001-46CB3ED2D36F,4DA5FA6D-8496-4D75-AA6A-4C32B377BDF9,C5868274-5850-4762-8EA8-5B5B7C1C2B5B,BD15D85F-F591-4AB5-881A-65E296715D18,33A67A70-9935-4214-B7B0-69B7AC228F5C,26C1ACD4-C763-40E0-AA10-6DEB1F960A9A,46F9F76A-1324-474B-B0BD-6E160C3E8ACD,7DA9883A-47B8-4640-99F7-7145A3A6A936,EB5F8AE0-FC95-4D38-87FE-801C22911CA6,2D68CB77-FE15-4030-839A-824B6D0806BA,9A615ECD-2389-4D20-B0BE-8667626A38BA,CF6E7729-C9E7-4373-BEAB-895D9A2F1379,8288801A-186F-4BE4-A044-8A4007BD2372,0BBEF81F-92A9-4183-A354-8B15F4B354DD,DF0D3E78-19EB-4779-BAE8-A974FE4F1B33,F5F18987-540E-44A0-A9EB-BC42699EFA30,2E7A5E82-702A-4003-BB17-C072A93ED941,14FFFD59-D749-4233-8D10-C0E314B69DDF,18750389-36C6-4D3E-BE79-C54B859CE83B,2C63EBDD-07D4-4F26-A3A4-C5E18DBCB5CF,0A293ED6-5DE5-4B92-BDF0-C8357DF9003D,D103A123-A2A2-4EF1-97DF-D184E971FE7B,448A0BB2-7D2C-4F24-97A4-D41A313298D9,C98B01D1-B2E7-4378-A1A4-D5245CDDDF0D,24BC285F-E14C-491F-8F76-D8D1CCDA99CD,3AAEA81D-20C4-4F24-B022-DECA9C7C51B1,5081472D-203E-4F21-9CF8-E1F98619361A,767BE8C9-EE38-4652-BB9B-E7132E63750C,70F9D814-5DD6-4901-8433-E7F8A4D61658,2FCEFF0C-E82D-4E02-8A8F-EE571D0BB7CF,0903AD78-75EB-4535-8935-FC528263D256,1860348D-20B5-42CF-BA66-203864BA0461,401CD56D-0E45-47C1-B982-37A277394749,26C1ACD4-C763-40E0-AA10-6DEB1F960A9A,7DA9883A-47B8-4640-99F7-7145A3A6A936,9A615ECD-2389-4D20-B0BE-8667626A38BA,DF0D3E78-19EB-4779-BAE8-A974FE4F1B33,2E7A5E82-702A-4003-BB17-C072A93ED941,14FFFD59-D749-4233-8D10-C0E314B69DDF,0A293ED6-5DE5-4B92-BDF0-C8357DF9003D,C98B01D1-B2E7-4378-A1A4-D5245CDDDF0D,24BC285F-E14C-491F-8F76-D8D1CCDA99CD,3AAEA81D-20C4-4F24-B022-DECA9C7C51B1,767BE8C9-EE38-4652-BB9B-E7132E63750C,2FCEFF0C-E82D-4E02-8A8F-EE571D0BB7CF,0903AD78-75EB-4535-8935-FC528263D256'
--SET @dids = NULL
--SET	@rprtcfgid = N'E671E529-196F-4C6A-83FE-5F51B1257862'
--SET @sdate = '2020-04-07 00:00'
--SET @edate = '2020-04-07 23:59'
--SET @uid = N'3DB40C4A-7E79-4F41-8017-DE6E12EC7A20'

DECLARE	@lvids varchar(max),
		@ldids VARCHAR(MAX),
		@lsdate datetime,
		@ledate datetime,
		@luid uniqueidentifier,
		@lrprtcfgid UNIQUEIDENTIFIER
		
SET @lvids = @vids
SET @ldids = @dids
SET @lsdate = @sdate
SET @ledate = @edate
SET @luid = @uid
SET @lrprtcfgid = @rprtcfgid


DECLARE @lfleet NVARCHAR(MAX)
SET @lfleet = ''

SELECT @lfleet = COALESCE(@lfleet + CASE WHEN @lfleet = '' THEN '' ELSE ',' END, '') + CAST(v.VehicleId AS NVARCHAR(MAX))
FROM dbo.[Group] g
	INNER JOIN dbo.UserGroup ug ON ug.GroupId = g.GroupId
	INNER JOIN dbo.GroupDetail gd ON gd.GroupId = g.GroupId
	INNER JOIN dbo.Vehicle v ON gd.EntityDataId = v.VehicleId
WHERE g.IsParameter = 0 AND g.GroupTypeId = 1 
	AND v.Archived = 0 
	AND ug.UserId = @luid
	AND ug.Archived = 0


DECLARE @diststr varchar(20),
		@distmult float,
		@fuelstr varchar(20),
		@fuelmult float,
		@co2str varchar(20),
		@co2mult float

SELECT @diststr = [dbo].UserPref(@luid, 203)
SELECT @distmult = [dbo].UserPref(@luid, 202)
SELECT @fuelstr = [dbo].UserPref(@luid, 205)
SELECT @fuelmult = [dbo].UserPref(@luid, 204)
SELECT @co2str = [dbo].UserPref(@luid, 211)
SELECT @co2mult = [dbo].UserPref(@luid, 210)
		
DECLARE @ResultsVehicles TABLE 
	(
		VehicleId UNIQUEIDENTIFIER,	
		Registration VARCHAR(MAX),
		VehicleTypeID INT,
		DriverId UNIQUEIDENTIFIER,
 		DisplayName VARCHAR(MAX),
 		DriverName VARCHAR(MAX), 
 		FirstName VARCHAR(MAX),
 		Surname VARCHAR(MAX),
 		MiddleNames VARCHAR(MAX),
 		Number VARCHAR(MAX),
 		NumberAlternate VARCHAR(MAX),
 		NumberAlternate2 VARCHAR(MAX),
		ReportConfigId UNIQUEIDENTIFIER,
		SweetSpot FLOAT, 
		OverRevWithFuel FLOAT, 
		TopGear FLOAT, 
		Cruise FLOAT,
		CruiseInTopGears FLOAT, 
		CoastInGear FLOAT, 
		Idle FLOAT, 
		EngineServiceBrake FLOAT, 
		OverRevWithoutFuel FLOAT, 
		Rop FLOAT, 
		Rop2 FLOAT,
		OverSpeed FLOAT,
		OverSpeedHigh FLOAT,
		OverSpeedDistance FLOAT, 
		IVHOverSpeed FLOAT,
		CoastOutOfGear FLOAT, 
		HarshBraking FLOAT, 
		FuelEcon FLOAT,
		Pto FLOAT, 
		Co2 FLOAT, 
		CruiseTopGearRatio FLOAT,
		Acceleration FLOAT, 
		Braking FLOAT, 
		Cornering FLOAT,
		AccelerationLow FLOAT, 
		BrakingLow FLOAT, 
		CorneringLow FLOAT,
		AccelerationHigh FLOAT, 
		BrakingHigh FLOAT, 
		CorneringHigh FLOAT,
		ManoeuvresLow FLOAT,
		ManoeuvresMed FLOAT,
		CruiseOverspeed FLOAT,
		TopGearOverspeed FLOAT,
		FuelWastageCost FLOAT,

	OverspeedCount FLOAT,
	OverspeedHighCount FLOAT,
	StabilityControl FLOAT,
	CollisionWarningLow FLOAT,
	CollisionWarningMed FLOAT,
	CollisionWarningHigh FLOAT,
	LaneDepartureDisable FLOAT,
	LaneDepartureLeftRight FLOAT,
	Fatigue FLOAT,
	Distraction FLOAT,
	SweetSpotTime FLOAT,
	OverRevTime FLOAT,
	TopGearTime FLOAT,

		SweetSpotComponent FLOAT,
		OverRevWithFuelComponent FLOAT,
		TopGearComponent FLOAT,
		CruiseComponent FLOAT,
		CruiseInTopGearsComponent FLOAT,
		IdleComponent FLOAT,
		EngineServiceBrakeComponent FLOAT,
		OverRevWithoutFuelComponent FLOAT,
		RopComponent FLOAT,
		Rop2Component FLOAT,
		OverSpeedComponent FLOAT,
		OverSpeedHighComponent FLOAT,
		OverSpeedDistanceComponent FLOAT,
		IVHOverSpeedComponent FLOAT,
		CoastOutOfGearComponent FLOAT,
		HarshBrakingComponent FLOAT,
		AccelerationComponent FLOAT,
		BrakingComponent FLOAT,
		CorneringComponent FLOAT,
		AccelerationLowComponent FLOAT,
		BrakingLowComponent FLOAT,
		CorneringLowComponent FLOAT,
		AccelerationHighComponent FLOAT,
		BrakingHighComponent FLOAT,
		CorneringHighComponent FLOAT,
		ManoeuvresLowComponent FLOAT,
		ManoeuvresMedComponent FLOAT,
		CruiseOverspeedComponent FLOAT,
		TopGearOverspeedComponent FLOAT,

	OverspeedCountComponent FLOAT,
	OverspeedHighCountComponent FLOAT,
	StabilityControlComponent FLOAT,
	CollisionWarningLowComponent FLOAT,
	CollisionWarningMedComponent FLOAT,
	CollisionWarningHighComponent FLOAT,
	LaneDepartureDisableComponent FLOAT,
	LaneDepartureLeftRightComponent FLOAT,
	FatigueComponent FLOAT,
	DistractionComponent FLOAT,
	SweetSpotTimeComponent FLOAT,
	OverRevTimeComponent FLOAT,
	TopGearTimeComponent FLOAT,

		Efficiency FLOAT, 
		Safety FLOAT,

		TotalTime FLOAT,
		TotalDrivingDistance FLOAT,
		ServiceBrakeUsage FLOAT,	
		OverRevCount FLOAT,
		sdate DATETIME,
		edate DATETIME,
		CreationDateTime DATETIME,
		ClosureDateTime DATETIME,
		DistanceUnit VARCHAR(MAX),
		FuelUnit VARCHAR(MAX),
		Co2Unit VARCHAR(MAX),
		FuelMult FLOAT,
		Currency NVARCHAR(10),
		SweetSpotColour VARCHAR(MAX),
		SweetSpotMix BIT,
		OverRevWithFuelColour VARCHAR(MAX),
		OverRevWithFuelMix BIT,
		TopGearColour VARCHAR(MAX),
		TopGearMix BIT,
		CruiseColour VARCHAR(MAX),
		CruiseMix BIT,
		CruiseInTopGearsColour NVARCHAR(MAX),
		CruiseInTopGearsMix BIT,
		CoastInGearColour VARCHAR(MAX),
		CoastInGearMix BIT,
		IdleColour VARCHAR(MAX),
		IdleMix BIT,
		EngineServiceBrakeColour VARCHAR(MAX),
		EngineServiceBrakeMix BIT,	
		OverRevWithoutFuelColour VARCHAR(MAX),
		OverRevWithoutFuelMix BIT,
		RopColour VARCHAR(MAX),
		RopMix BIT,
		Rop2Colour VARCHAR(MAX),
		Rop2Mix BIT,
		OverSpeedColour VARCHAR(MAX), 
		OverSpeedMix BIT,
		OverSpeedHighColour NVARCHAR(MAX),
		OverSpeedHighMix BIT,
		IVHOverSpeedColour VARCHAR(MAX),
		IVHOverSpeedMix BIT,
		CoastOutOfGearColour VARCHAR(MAX),
		CoastOutOfGearMix BIT,
		HarshBrakingColour VARCHAR(MAX),
		HarshBrakingMix BIT,
		EfficiencyColour VARCHAR(MAX),
		EfficiencyMix BIT,
		SafetyColour VARCHAR(MAX),
		SafetyMix BIT,
		KPLColour VARCHAR(MAX),
		KPLMix BIT,
		Co2Colour VARCHAR(MAX),
		Co2Mix BIT,
		OverSpeedDistanceColour VARCHAR(MAX),
		OverSpeedDistanceMix BIT,
		AccelerationColour VARCHAR(MAX),
		AccelerationMix BIT,
		BrakingColour VARCHAR(MAX),
		BrakingMix BIT,
		CorneringColour VARCHAR(MAX),
		CorneringMix BIT,
		AccelerationLowColour VARCHAR(MAX),
		AccelerationLowMix BIT,
		BrakingLowColour VARCHAR(MAX),
		BrakingLowMix BIT,
		CorneringLowColour VARCHAR(MAX),
		CorneringLowMix BIT,
		AccelerationHighColour VARCHAR(MAX),
		AccelerationHighMix BIT,
		BrakingHighColour VARCHAR(MAX),
		BrakingHighMix BIT,
		CorneringHighColour VARCHAR(MAX),
		CorneringHighMix BIT,
		ManoeuvresLowColour VARCHAR(MAX),
		ManoeuvresLowMix BIT,
		ManoeuvresMedColour VARCHAR(MAX),
		ManoeuvresMedMix BIT,
		CruiseTopGearRatioColour VARCHAR(MAX),
		CruiseTopGearRatioMix BIT,
		OverRevCountColour VARCHAR(MAX),
		OverRevCountMix BIT,
		PtoColour VARCHAR(MAX),
		PtoMix BIT,
		CruiseOverspeedColour VARCHAR(MAX),
		CruiseOverspeedMix BIT,
		TopGearOverspeedColour VARCHAR(MAX),
		TopGearOverspeedMix BIT,
		FuelWastageCostColour VARCHAR(MAX),

	OverspeedCountColour VARCHAR(MAX),
	OverspeedCountMix BIT,
	OverspeedHighCountColour VARCHAR(MAX),
	OverspeedHighCountMix BIT,
	StabilityControlColour VARCHAR(MAX),
	StabilityControlMix BIT,
	CollisionWarningLowColour VARCHAR(MAX),
	CollisionWarningLowMix BIT,
	CollisionWarningMedColour VARCHAR(MAX),
	CollisionWarningMedMix BIT,
	CollisionWarningHighColour VARCHAR(MAX),
	CollisionWarningHighMix BIT,
	LaneDepartureDisableColour VARCHAR(MAX),
	LaneDepartureDisableMix BIT,
	LaneDepartureLeftRightColour VARCHAR(MAX),
	LaneDepartureLeftRightMix BIT,
	FatigueColour VARCHAR(MAX),
	FatigueMix BIT,
	DistractionColour VARCHAR(MAX),
	DistractionMix BIT,
	SweetSpotTimeColour VARCHAR(MAX),
	SweetSpotTimeMix BIT,
	OverRevTimeColour VARCHAR(MAX),
	OverRevTimeMix BIT,
	TopGearTimeColour VARCHAR(MAX),
	TopGearTimeMix BIT
	)


INSERT INTO @ResultsVehicles
EXEC proc_ReportByVehicleConfigId @lvids, @ldids, @lsdate, @ledate, @luid, @lrprtcfgid

DECLARE @ResultsFleet TABLE 
	(
		VehicleId UNIQUEIDENTIFIER,	
		Registration VARCHAR(MAX),
		VehicleTypeID INT,
		DriverId UNIQUEIDENTIFIER,
 		DisplayName VARCHAR(MAX),
 		DriverName VARCHAR(MAX), 
 		FirstName VARCHAR(MAX),
 		Surname VARCHAR(MAX),
 		MiddleNames VARCHAR(MAX),
 		Number VARCHAR(MAX),
 		NumberAlternate VARCHAR(MAX),
 		NumberAlternate2 VARCHAR(MAX),
		ReportConfigId UNIQUEIDENTIFIER,
		SweetSpot FLOAT, 
		OverRevWithFuel FLOAT, 
		TopGear FLOAT, 
		Cruise FLOAT,
		CruiseInTopGears FLOAT, 
		CoastInGear FLOAT, 
		Idle FLOAT, 
		EngineServiceBrake FLOAT, 
		OverRevWithoutFuel FLOAT, 
		Rop FLOAT, 
		Rop2 FLOAT,
		OverSpeed FLOAT,
		OverSpeedHigh FLOAT,
		OverSpeedDistance FLOAT, 
		IVHOverSpeed FLOAT,
		CoastOutOfGear FLOAT, 
		HarshBraking FLOAT, 
		FuelEcon FLOAT,
		Pto FLOAT, 
		Co2 FLOAT, 
		CruiseTopGearRatio FLOAT,
		Acceleration FLOAT, 
		Braking FLOAT, 
		Cornering FLOAT,
		AccelerationLow FLOAT, 
		BrakingLow FLOAT, 
		CorneringLow FLOAT,
		AccelerationHigh FLOAT, 
		BrakingHigh FLOAT, 
		CorneringHigh FLOAT,
		ManoeuvresLow FLOAT,
		ManoeuvresMed FLOAT,
		CruiseOverspeed FLOAT,
		TopGearOverspeed FLOAT,
		FuelWastageCost FLOAT,

	OverspeedCount FLOAT,
	OverspeedHighCount FLOAT,
	StabilityControl FLOAT,
	CollisionWarningLow FLOAT,
	CollisionWarningMed FLOAT,
	CollisionWarningHigh FLOAT,
	LaneDepartureDisable FLOAT,
	LaneDepartureLeftRight FLOAT,
	Fatigue FLOAT,
	Distraction FLOAT,
	SweetSpotTime FLOAT,
	OverRevTime FLOAT,
	TopGearTime FLOAT,

		SweetSpotComponent FLOAT,
		OverRevWithFuelComponent FLOAT,
		TopGearComponent FLOAT,
		CruiseComponent FLOAT,
		CruiseInTopGearsComponent FLOAT,
		IdleComponent FLOAT,
		EngineServiceBrakeComponent FLOAT,
		OverRevWithoutFuelComponent FLOAT,
		RopComponent FLOAT,
		Rop2Component FLOAT,
		OverSpeedComponent FLOAT,
		OverSpeedHighComponent FLOAT,
		OverSpeedDistanceComponent FLOAT,
		IVHOverSpeedComponent FLOAT,
		CoastOutOfGearComponent FLOAT,
		HarshBrakingComponent FLOAT,
		AccelerationComponent FLOAT,
		BrakingComponent FLOAT,
		CorneringComponent FLOAT,
		AccelerationLowComponent FLOAT,
		BrakingLowComponent FLOAT,
		CorneringLowComponent FLOAT,
		AccelerationHighComponent FLOAT,
		BrakingHighComponent FLOAT,
		CorneringHighComponent FLOAT,
		ManoeuvresLowComponent FLOAT,
		ManoeuvresMedComponent FLOAT,
		CruiseOverspeedComponent FLOAT,
		TopGearOverspeedComponent FLOAT,

	OverspeedCountComponent FLOAT,
	OverspeedHighCountComponent FLOAT,
	StabilityControlComponent FLOAT,
	CollisionWarningLowComponent FLOAT,
	CollisionWarningMedComponent FLOAT,
	CollisionWarningHighComponent FLOAT,
	LaneDepartureDisableComponent FLOAT,
	LaneDepartureLeftRightComponent FLOAT,
	FatigueComponent FLOAT,
	DistractionComponent FLOAT,
	SweetSpotTimeComponent FLOAT,
	OverRevTimeComponent FLOAT,
	TopGearTimeComponent FLOAT,

		Efficiency FLOAT, 
		Safety FLOAT,

		TotalTime FLOAT,
		TotalDrivingDistance FLOAT,
		ServiceBrakeUsage FLOAT,	
		OverRevCount FLOAT,
		sdate DATETIME,
		edate DATETIME,
		CreationDateTime DATETIME,
		ClosureDateTime DATETIME,
		DistanceUnit VARCHAR(MAX),
		FuelUnit VARCHAR(MAX),
		Co2Unit VARCHAR(MAX),
		FuelMult FLOAT,
		Currency NVARCHAR(10),
		SweetSpotColour VARCHAR(MAX),
		SweetSpotMix BIT,
		OverRevWithFuelColour VARCHAR(MAX),
		OverRevWithFuelMix BIT,
		TopGearColour VARCHAR(MAX),
		TopGearMix BIT,
		CruiseColour VARCHAR(MAX),
		CruiseMix BIT,
		CruiseInTopGearsColour NVARCHAR(MAX),
		CruiseInTopGearsMix BIT,
		CoastInGearColour VARCHAR(MAX),
		CoastInGearMix BIT,
		IdleColour VARCHAR(MAX),
		IdleMix BIT,
		EngineServiceBrakeColour VARCHAR(MAX),
		EngineServiceBrakeMix BIT,	
		OverRevWithoutFuelColour VARCHAR(MAX),
		OverRevWithoutFuelMix BIT,
		RopColour VARCHAR(MAX),
		RopMix BIT,
		Rop2Colour VARCHAR(MAX),
		Rop2Mix BIT,
		OverSpeedColour VARCHAR(MAX), 
		OverSpeedMix BIT,
		OverSpeedHighColour NVARCHAR(MAX),
		OverSpeedHighMix BIT,
		IVHOverSpeedColour VARCHAR(MAX),
		IVHOverSpeedMix BIT,
		CoastOutOfGearColour VARCHAR(MAX),
		CoastOutOfGearMix BIT,
		HarshBrakingColour VARCHAR(MAX),
		HarshBrakingMix BIT,
		EfficiencyColour VARCHAR(MAX),
		EfficiencyMix BIT,
		SafetyColour VARCHAR(MAX),
		SafetyMix BIT,
		KPLColour VARCHAR(MAX),
		KPLMix BIT,
		Co2Colour VARCHAR(MAX),
		Co2Mix BIT,
		OverSpeedDistanceColour VARCHAR(MAX),
		OverSpeedDistanceMix BIT,
		AccelerationColour VARCHAR(MAX),
		AccelerationMix BIT,
		BrakingColour VARCHAR(MAX),
		BrakingMix BIT,
		CorneringColour VARCHAR(MAX),
		CorneringMix BIT,
		AccelerationLowColour VARCHAR(MAX),
		AccelerationLowMix BIT,
		BrakingLowColour VARCHAR(MAX),
		BrakingLowMix BIT,
		CorneringLowColour VARCHAR(MAX),
		CorneringLowMix BIT,
		AccelerationHighColour VARCHAR(MAX),
		AccelerationHighMix BIT,
		BrakingHighColour VARCHAR(MAX),
		BrakingHighMix BIT,
		CorneringHighColour VARCHAR(MAX),
		CorneringHighMix BIT,
		ManoeuvresLowColour VARCHAR(MAX),
		ManoeuvresLowMix BIT,
		ManoeuvresMedColour VARCHAR(MAX),
		ManoeuvresMedMix BIT,
		CruiseTopGearRatioColour VARCHAR(MAX),
		CruiseTopGearRatioMix BIT,
		OverRevCountColour VARCHAR(MAX),
		OverRevCountMix BIT,
		PtoColour VARCHAR(MAX),
		PtoMix BIT,
		CruiseOverspeedColour VARCHAR(MAX),
		CruiseOverspeedMix BIT,
		TopGearOverspeedColour VARCHAR(MAX),
		TopGearOverspeedMix BIT,
		FuelWastageCostColour VARCHAR(MAX),

	OverspeedCountColour VARCHAR(MAX),
	OverspeedCountMix BIT,
	OverspeedHighCountColour VARCHAR(MAX),
	OverspeedHighCountMix BIT,
	StabilityControlColour VARCHAR(MAX),
	StabilityControlMix BIT,
	CollisionWarningLowColour VARCHAR(MAX),
	CollisionWarningLowMix BIT,
	CollisionWarningMedColour VARCHAR(MAX),
	CollisionWarningMedMix BIT,
	CollisionWarningHighColour VARCHAR(MAX),
	CollisionWarningHighMix BIT,
	LaneDepartureDisableColour VARCHAR(MAX),
	LaneDepartureDisableMix BIT,
	LaneDepartureLeftRightColour VARCHAR(MAX),
	LaneDepartureLeftRightMix BIT,
	FatigueColour VARCHAR(MAX),
	FatigueMix BIT,
	DistractionColour VARCHAR(MAX),
	DistractionMix BIT,
	SweetSpotTimeColour VARCHAR(MAX),
	SweetSpotTimeMix BIT,
	OverRevTimeColour VARCHAR(MAX),
	OverRevTimeMix BIT,
	TopGearTimeColour VARCHAR(MAX),
	TopGearTimeMix BIT
	)

INSERT INTO @ResultsFleet
EXEC proc_ReportByVehicleConfigId @lfleet, @ldids, @lsdate, @ledate, @luid, @lrprtcfgid

-- Calculate Score and Colours for Report Total
UPDATE @ResultsFleet
SET Efficiency = w.WeightedEfficiency / d.TotalDrivingDistance, 
	Safety = w.WeightedSafety / d.TotalDrivingDistance
FROM @ResultsFleet d
CROSS JOIN 
	(SELECT SUM(d.Efficiency * d.TotalDrivingDistance) AS WeightedEfficiency, SUM(d.Safety * d.TotalDrivingDistance) AS WeightedSafety
	FROM @ResultsFleet d
	WHERE d.VehicleId IS NOT NULL AND d.DriverId IS NULL) w 
WHERE d.DriverId IS NULL AND d.VehicleId IS NULL

SELECT	rv.*, 
		rf.Safety AS FleetSafety, 
		rf.Efficiency AS FleetEfficency,
		rf.EngineServiceBrake AS FleetEngineServiceBrake,
		rf.OverSpeed AS FleetOverSpeed,
		rf.OverSpeedHigh AS FleetOverSpeedHigh,
		rf.CoastOutOfGear AS FleetCoastOutOfGear,
		rf.Acceleration AS FleetAcceleration,
		rf.Braking AS FleetBraking,
		rf.Cornering AS FleetCornering,
		rf.SweetSpot AS FleetSweetSpot,
		rf.OverRevWithFuel AS FleetOverRevWithFuel,
		rf.TopGear AS FleetTopGear,
		rf.Cruise AS FleetCruise,
		rf.CruiseInTopGears AS FleetCruiseInTopGears,
		rf.Idle AS FleetIdle,
		rf.CruiseOverspeed AS FleetCruiseOverspeed,
		rf.TopGearOverspeed AS FleetTopGearOverspeed
FROM @ResultsVehicles rv
INNER JOIN @ResultsFleet rf ON ISNULL(rv.Registration, 'Total') = ISNULL(rf.Registration, 'Total') 
							AND ISNULL(rv.DriverName, 'Total') = ISNULL(rf.DriverName, 'Total')
WHERE rf.DriverId IS NULL
  AND rf.VehicleId IS NULL
  AND rv.DriverId IS NULL
  AND rv.VehicleId IS NULL



GO
