SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROC [dbo].[proc_BulkInsertEventVideo]
AS

--ALTER TABLE EventData NOCHECK CONSTRAINT ALL
INSERT INTO EventVideo SELECT * FROM EventVideoTemp WHERE Archived = 0
--ALTER TABLE EventData CHECK CONSTRAINT ALL



GO
