SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[proc_RDL_GetReportLogo](@UserID UNIQUEIDENTIFIER, @TypeID INTEGER)
AS
    SET NOCOUNT ON;

	-- declare @UserID UNIQUEIDENTIFIER, @TypeID INTEGER
	--select @UserID = N'EB1D6E4D-6A41-4100-A003-2FED0786D5C4', @TypeID = 12

	SELECT 0
	
					

GO
