SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[proc_BulkInsertSnapshot]
AS

--ALTER TABLE Snapshot NOCHECK CONSTRAINT ALL
INSERT INTO Snapshot SELECT * FROM SnapshotTemp WHERE Archived = 0
--ALTER TABLE Snapshot CHECK CONSTRAINT ALL

GO
