SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE PROCEDURE [dbo].[proc_SafetyReportABCbyVehicleGroup_Fair]
(
	@sdate DATETIME,
	@edate DATETIME,
	@gids NVARCHAR(MAX),
	@vids NVARCHAR(MAX),
	@uid UNIQUEIDENTIFIER,
	@rprtcfgid UNIQUEIDENTIFIER
)
AS

	--DECLARE @sdate DATETIME,
	--	@edate DATETIME,
	--	@gids NVARCHAR(MAX),
	--	@vids NVARCHAR(MAX),
	--	@uid UNIQUEIDENTIFIER,
	--	@rprtcfgid UNIQUEIDENTIFIER
	--SET @gids = N'906E3BAD-7739-44B1-8966-28F8D4F10A09'
	--SET @vids = N'8016F50D-A2D1-49A9-BC1E-13AE27953390,486A43F1-70D9-46CC-A745-542B6A4D77CE,5DE385BF-BFCB-4179-90CB-5AEE460B14AD,67B44E7F-6A0E-42E0-9DCF-5DDCA2AF502E,2C1A82DE-6DCB-4D03-BC21-5F65198B9A84,DB3AC174-1CFE-404C-914B-6BE9DB1B7038,D075F7EF-C02E-46E4-91C3-8191F2167F59,6CD1331B-F7FC-4866-A333-8FEE45667F33,91D26E73-DBD4-45DA-935C-997766C44AA2,3708F23A-F7CA-44F0-BB96-A94E80C40DFF'
	--SET @sdate = '2012-06-25 00:00'
	--SET @edate = '2012-07-05 23:59'
	--SET @uid = N'FE90CE6B-0973-4D7B-8157-1C89CFA422F5'
	--SET @rprtcfgid = N'72D4F529-420B-4C07-B13E-C214B84CFB71'


	DECLARE @ResultSet TABLE
	(
			GroupId UNIQUEIDENTIFIER,
			GroupName VARCHAR(MAX),
			GroupTypeID INT,
		
			ReportConfigId UNIQUEIDENTIFIER,

			SweetSpot FLOAT, 
			OverRevWithFuel FLOAT, 
			TopGear FLOAT, 
			Cruise FLOAT,
			CruiseInTopGears FLOAT, 
			CoastInGear FLOAT, 
			Idle FLOAT, 
			EngineServiceBrake FLOAT, 
			OverRevWithoutFuel FLOAT, 
			Rop FLOAT, 
			Rop2 FLOAT,
			OverSpeed FLOAT,
			OverSpeedHigh FLOAT,
			OverSpeedDistance FLOAT, 
			IVHOverSpeed FLOAT,
			CoastOutOfGear FLOAT, 
			HarshBraking FLOAT, 
			FuelEcon FLOAT,
			Pto FLOAT, 
			Co2 FLOAT, 
			CruiseTopGearRatio FLOAT,
			Acceleration FLOAT, 
			Braking FLOAT, 
			Cornering FLOAT,
			AccelerationLow FLOAT, 
			BrakingLow FLOAT, 
			CorneringLow FLOAT,
			AccelerationHigh FLOAT, 
			BrakingHigh FLOAT, 
			CorneringHigh FLOAT,
			ManoeuvresLow FLOAT,
			ManoeuvresMed FLOAT,
			CruiseOverspeed FLOAT,
			TopGearOverspeed FLOAT,
			FuelWastageCost FLOAT,

		OverspeedCount FLOAT,
		OverspeedHighCount FLOAT,
		StabilityControl FLOAT,
		CollisionWarningLow FLOAT,
		CollisionWarningMed FLOAT,
		CollisionWarningHigh FLOAT,
		LaneDepartureDisable FLOAT,
		LaneDepartureLeftRight FLOAT,
		Fatigue FLOAT,
		Distraction FLOAT,
		SweetSpotTime FLOAT,
		OverRevTime FLOAT,
		TopGearTime FLOAT,

			SweetSpotComponent FLOAT,
			OverRevWithFuelComponent FLOAT,
			TopGearComponent FLOAT,
			CruiseComponent FLOAT,
			CruiseInTopGearsComponent FLOAT,
			IdleComponent FLOAT,
			EngineServiceBrakeComponent FLOAT,
			OverRevWithoutFuelComponent FLOAT,
			RopComponent FLOAT,
			Rop2Component FLOAT,
			OverSpeedComponent FLOAT,
			OverSpeedHighComponent FLOAT,
			OverSpeedDistanceComponent FLOAT,
			IVHOverSpeedComponent FLOAT,
			CoastOutOfGearComponent FLOAT,
			HarshBrakingComponent FLOAT,
			AccelerationComponent FLOAT,
			BrakingComponent FLOAT,
			CorneringComponent FLOAT,
			AccelerationLowComponent FLOAT,
			BrakingLowComponent FLOAT,
			CorneringLowComponent FLOAT,
			AccelerationHighComponent FLOAT,
			BrakingHighComponent FLOAT,
			CorneringHighComponent FLOAT,
			ManoeuvresLowComponent FLOAT,
			ManoeuvresMedComponent FLOAT,
			CruiseOverspeedComponent FLOAT,
			TopGearOverspeedComponent FLOAT,

		OverspeedCountComponent FLOAT,
		OverspeedHighCountComponent FLOAT,
		StabilityControlComponent FLOAT,
		CollisionWarningLowComponent FLOAT,
		CollisionWarningMedComponent FLOAT,
		CollisionWarningHighComponent FLOAT,
		LaneDepartureDisableComponent FLOAT,
		LaneDepartureLeftRightComponent FLOAT,
		FatigueComponent FLOAT,
		DistractionComponent FLOAT,
		SweetSpotTimeComponent FLOAT,
		OverRevTimeComponent FLOAT,
		TopGearTimeComponent FLOAT,

			Efficiency FLOAT, 
			Safety FLOAT,

			TotalTime FLOAT,
			TotalDrivingDistance FLOAT,
			ServiceBrakeUsage FLOAT,	
			OverRevCount FLOAT,
			sdate DATETIME,
			edate DATETIME,
			CreationDateTime DATETIME,
			ClosureDateTime DATETIME,
			DistanceUnit VARCHAR(MAX),
			FuelUnit VARCHAR(MAX),
			Co2Unit VARCHAR(MAX),
			FuelMult FLOAT,
			--Currency NVARCHAR(10),
			SweetSpotColour VARCHAR(MAX),
			SweetSpotMix BIT,
			OverRevWithFuelColour VARCHAR(MAX),
			OverRevWithFuelMix BIT,
			TopGearColour VARCHAR(MAX),
			TopGearMix BIT,
			CruiseColour VARCHAR(MAX),
			CruiseMix BIT,
			CruiseInTopGearsColour NVARCHAR(MAX),
			CruiseInTopGearsMix BIT,
			CoastInGearColour VARCHAR(MAX),
			CoastInGearMix BIT,
			IdleColour VARCHAR(MAX),
			IdleMix BIT,
			EngineServiceBrakeColour VARCHAR(MAX),
			EngineServiceBrakeMix BIT,	
			OverRevWithoutFuelColour VARCHAR(MAX),
			OverRevWithoutFuelMix BIT,
			RopColour VARCHAR(MAX),
			RopMix BIT,
			Rop2Colour VARCHAR(MAX),
			Rop2Mix BIT,
			OverSpeedColour VARCHAR(MAX), 
			OverSpeedMix BIT,
			OverSpeedHighColour NVARCHAR(MAX),
			OverSpeedHighMix BIT,
			IVHOverSpeedColour VARCHAR(MAX),
			IVHOverSpeedMix BIT,
			CoastOutOfGearColour VARCHAR(MAX),
			CoastOutOfGearMix BIT,
			HarshBrakingColour VARCHAR(MAX),
			HarshBrakingMix BIT,
			EfficiencyColour VARCHAR(MAX),
			EfficiencyMix BIT,
			SafetyColour VARCHAR(MAX),
			SafetyMix BIT,
			KPLColour VARCHAR(MAX),
			KPLMix BIT,
			Co2Colour VARCHAR(MAX),
			Co2Mix BIT,
			OverSpeedDistanceColour VARCHAR(MAX),
			OverSpeedDistanceMix BIT,
			AccelerationColour VARCHAR(MAX),
			AccelerationMix BIT,
			BrakingColour VARCHAR(MAX),
			BrakingMix BIT,
			CorneringColour VARCHAR(MAX),
			CorneringMix BIT,
			AccelerationLowColour VARCHAR(MAX),
			AccelerationLowMix BIT,
			BrakingLowColour VARCHAR(MAX),
			BrakingLowMix BIT,
			CorneringLowColour VARCHAR(MAX),
			CorneringLowMix BIT,
			AccelerationHighColour VARCHAR(MAX),
			AccelerationHighMix BIT,
			BrakingHighColour VARCHAR(MAX),
			BrakingHighMix BIT,
			CorneringHighColour VARCHAR(MAX),
			CorneringHighMix BIT,
			ManoeuvresLowColour VARCHAR(MAX),
			ManoeuvresLowMix BIT,
			ManoeuvresMedColour VARCHAR(MAX),
			ManoeuvresMedMix BIT,
			CruiseTopGearRatioColour VARCHAR(MAX),
			CruiseTopGearRatioMix BIT,
			OverRevCountColour VARCHAR(MAX),
			OverRevCountMix BIT,
			PtoColour VARCHAR(MAX),
			PtoMix BIT,
			CruiseOverspeedColour VARCHAR(MAX),
			CruiseOverspeedMix BIT,
			TopGearOverspeedColour VARCHAR(MAX),
			TopGearOverspeedMix BIT,
			FuelWastageCostColour VARCHAR(MAX),

		OverspeedCountColour VARCHAR(MAX),
		OverspeedCountMix BIT,
		OverspeedHighCountColour VARCHAR(MAX),
		OverspeedHighCountMix BIT,
		StabilityControlColour VARCHAR(MAX),
		StabilityControlMix BIT,
		CollisionWarningLowColour VARCHAR(MAX),
		CollisionWarningLowMix BIT,
		CollisionWarningMedColour VARCHAR(MAX),
		CollisionWarningMedMix BIT,
		CollisionWarningHighColour VARCHAR(MAX),
		CollisionWarningHighMix BIT,
		LaneDepartureDisableColour VARCHAR(MAX),
		LaneDepartureDisableMix BIT,
		LaneDepartureLeftRightColour VARCHAR(MAX),
		LaneDepartureLeftRightMix BIT,
		FatigueColour VARCHAR(MAX),
		FatigueMix BIT,
		DistractionColour VARCHAR(MAX),
		DistractionMix BIT,
		SweetSpotTimeColour VARCHAR(MAX),
		SweetSpotTimeMix BIT,
		OverRevTimeColour VARCHAR(MAX),
		OverRevTimeMix BIT,
		TopGearTimeColour VARCHAR(MAX),
		TopGearTimeMix BIT
	)

	INSERT INTO @ResultSet
	EXECUTE [dbo].[proc_ReportByvehicleConfigId_VehicleGroups] 
	   @gids
	  ,@vids
	  ,@sdate
	  ,@edate
	  ,@uid
	  ,@rprtcfgid


	DECLARE @scoreRounding INT,
			@abcRounding INT

	SET @scoreRounding = CASE WHEN CAST(ISNULL([dbo].UserPref(@uid, 217), '0') AS INT) = 1 THEN 2 ELSE 0 END
	SET @abcRounding = CASE WHEN CAST(ISNULL([dbo].UserPref(@uid, 218), '0') AS INT) = 1 THEN 2 ELSE 0 END

	SELECT 
		NULL as DepotName,
		NULL as DepotId,
		NULL AS InternalId,
		NULL AS Identifier,
		NULL AS VehicleTypeID,
		r1.GroupName,
		r1.GroupId,
		r1.GroupTypeID,
		r1.sdate,
		r1.edate,
		r1.CreationDateTime,
		r1.ClosureDateTime,
		r1.DistanceUnit,
		r1.TotalDrivingDistance,
		r1.Safety,
		r1.CoastInGear,
		r1.OverSpeed AS OverSpeedDistance,
		r1.OverSpeedHigh,
		r1.IVHOverSpeed AS IVHOverSpeedDistance,
		r1.Rop AS RopCount,
		r1.Rop2 AS Rop2Count,
		r1.HarshBraking,
		r1.Acceleration,
		r1.Braking,
		r1.Cornering,
		r1.AccelerationHigh,
		r1.BrakingHigh,
		r1.CorneringHigh,
		r1.ManoeuvresLow,
		r1.ManoeuvresMed,
		r1.EngineServiceBrake,
		r1.OverRevWithoutFuel,
		r1.CoastOutOfGear,
		r1.OverRevCount,
	
		r1.SafetyColour,
		r1.CoastInGearColour,
		r1.OverSpeedColour AS OverSpeedDistanceColour,
		r1.OverSpeedHighColour,
		r1.IVHOverSpeedColour AS IVHOverSpeedDistanceColour,
		r1.RopColour AS RopCountColour,
		r1.Rop2Colour AS Rop2CountColour,
		r1.HarshBrakingColour,
		r1.AccelerationColour,
		r1.BrakingColour,
		r1.CorneringColour,
		r1.AccelerationHighColour,
		r1.BrakingHighColour,
		r1.CorneringHighColour,
		r1.ManoeuvresLowColour,
		r1.ManoeuvresMedColour,
		r1.EngineServiceBrakeColour,
		r1.OverRevWithoutFuelColour,
		r1.CoastOutOfGearColour,
		r1.OverRevCountColour,
	
		ent.TotalDrivingDistance as TotalDrivingDistanceEntity,
		ent.Safety as SafetyEntity,
		ent.CoastInGear as CoastInGearEntity,
		ent.OverSpeed as OverSpeedDistanceEntity,
		ent.OverSpeedHigh AS OverSpeedHighEntity,
		ent.IVHOverSpeed as IVHOverSpeedDistanceEntity,
		ent.Rop AS RopCountEntity,
		ent.Rop2 AS Rop2CountEntity,
		ent.HarshBraking AS HarshBrakingEntity,
		ent.Acceleration as AccelerationEntity,
		ent.Braking as BrakingEntity,
		ent.Cornering as CorneringEntity,
		ent.AccelerationHigh as AccelerationHighEntity,
		ent.BrakingHigh as BrakingHighEntity,
		ent.CorneringHigh as CorneringHighEntity,
		ent.ManoeuvresLow as ManoeuvresLowEntity,
		ent.ManoeuvresMed as ManoeuvresMedEntity,
		ent.EngineServiceBrake AS EngineServiceBrakeEntity,
		ent.OverRevWithoutFuel AS OverRevWithoutFuelEntity,
		ent.CoastOutOfGear AS CoastOutOfGearEntity,
		ent.OverRevCount AS OverRevCountEntity,
		
    ent.OverspeedCount AS OverspeedCountEntity,
    ent.OverspeedHighCount AS OverspeedHighCountEntity,
    ent.StabilityControl AS StabilityControlEntity,
    ent.CollisionWarningLow AS CollisionWarningLowEntity,
    ent.CollisionWarningMed AS CollisionWarningMedEntity,
    ent.CollisionWarningHigh AS CollisionWarningHighEntity,
    ent.LaneDepartureDisable AS LaneDepartureDisableEntity,
    ent.LaneDepartureLeftRight AS LaneDepartureLeftRightEntity,
    ent.Fatigue AS FatigueEntity,
    ent.Distraction AS DistractionEntity,
    ent.SweetSpotTime AS SweetSpotTimeEntity, 
    ent.OverRevTime AS OverRevTimeEntity,
    ent.TopGearTime AS TopGearTimeEntity,
	
		ent.SafetyColour as SafetyColourEntity,
		ent.CoastInGearColour as CoastInGearColourEntity,
		ent.OverSpeedColour as OverSpeedDistanceColourEntity,
		ent.OverSpeedHighColour AS OverSpeedHighColourEntity,
		ent.IVHOverSpeedColour as IVHOverSpeedDistanceColourEntity,
		ent.RopColour AS RopCountColourEntity,
		ent.Rop2Colour AS Rop2CountColourEntity,
		ent.HarshBrakingColour AS HarshBrakingColourEntity,
		ent.AccelerationColour as AccelerationColourEntity,
		ent.BrakingColour as BrakingColourEntity,
		ent.CorneringColour as CorneringColourEntity,
		ent.AccelerationHighColour as AccelerationHighColourEntity,
		ent.BrakingHighColour as BrakingHighColourEntity,
		ent.CorneringHighColour as CorneringHighColourEntity,
		ent.ManoeuvresLowColour as ManoeuvresLowColourEntity,
		ent.ManoeuvresMedColour as ManoeuvresMedColourEntity,
		ent.EngineServiceBrakeColour AS EngineServiceBrakeColourEntity,
		ent.OverRevWithoutFuelColour AS OverRevWithoutFuelColourEntity,
		ent.CoastOutOfGearColour AS CoastOutOfGearColourEntity,
		ent.OverRevCountColour AS OverRevCountColourEntity,

    ent.OverspeedCountColour AS OverspeedCountColourEntity,
    ent.OverspeedHighCountColour AS OverspeedHighCountColourEntity,
    ent.StabilityControlColour AS StabilityControlColourEntity,
    ent.CollisionWarningLowColour AS CollisionWarningLowColourEntity,
    ent.CollisionWarningMedColour AS CollisionWarningMedColourEntity,
    ent.CollisionWarningHighColour AS CollisionWarningHighColourEntity,
    ent.LaneDepartureDisableColour AS LaneDepartureDisableColourEntity,
    ent.LaneDepartureLeftRightColour AS LaneDepartureLeftRightColourEntity,
    ent.FatigueColour AS FatigueColourEntity,
    ent.DistractionColour AS DistractionColourEntity,
    ent.SweetSpotTimeColour AS SweetSpotTimeColourEntity, 
    ent.OverRevTimeColour AS OverRevTimeColourEntity,
    ent.TopGearTimeColour AS TopGearTimeColourEntity,
	
		rep.TotalDrivingDistance as TotalDrivingDistanceReport,
		rep.Safety as SafetyReport,
		rep.CoastInGear as CoastInGearReport,
		rep.OverSpeed as OverSpeedDistanceReport,
		rep.OverSpeedHigh AS OverSpeedHighReport,
		rep.IVHOverSpeed as IVHOverSpeedDistanceReport,
		rep.Rop AS RopCountReport,
		rep.Rop2 AS Rop2CountReport,
		rep.HarshBraking AS HarshBrakingReport,
		rep.Acceleration as AccelerationReport,
		rep.Braking as BrakingReport,
		rep.Cornering as CorneringReport,
		rep.AccelerationHigh as AccelerationHighReport,
		rep.BrakingHigh as BrakingHighReport,
		rep.CorneringHigh as CorneringHighReport,
		rep.ManoeuvresLow as ManoeuvresLowReport,
		rep.ManoeuvresMed as ManoeuvresMedReport,
		rep.EngineServiceBrake AS EngineServiceBrakeReport,
		rep.OverRevWithoutFuel AS OverRevWithoutFuelReport,
		rep.CoastOutOfGear AS CoastOutOfGearReport,
		rep.OverRevCount AS OverRevCountReport,
		
    rep.OverspeedCount AS OverspeedCountReport,
    rep.OverspeedHighCount AS OverspeedHighCountReport,
    rep.StabilityControl AS StabilityControlReport,
    rep.CollisionWarningLow AS CollisionWarningLowReport,
    rep.CollisionWarningMed AS CollisionWarningMedReport,
    rep.CollisionWarningHigh AS CollisionWarningHighReport,
    rep.LaneDepartureDisable AS LaneDepartureDisableReport,
    rep.LaneDepartureLeftRight AS LaneDepartureLeftRightReport,
    rep.Fatigue AS FatigueReport,
    rep.Distraction AS DistractionReport,
    rep.SweetSpotTime AS SweetSpotTimeReport, 
    rep.OverRevTime AS OverRevTimeReport,
    rep.TopGearTime AS TopGearTimeReport,
	
		rep.SafetyColour as SafetyColourReport,
		rep.CoastInGearColour as CoastInGearColourReport,
		rep.OverSpeedColour as OverSpeedDistanceColourReport,
		rep.OverSpeedHighColour AS OverSpeedHighColourReport,
		rep.IVHOverSpeedColour as IVHOverSpeedDistanceColourReport,
		rep.RopColour AS RopCountColourReport,
		rep.Rop2Colour AS Rop2CountColourReport,
		rep.HarshBrakingColour AS HarshBrakingColourReport,
		rep.AccelerationColour as AccelerationColourReport,
		rep.BrakingColour as BrakingColourReport,
		rep.CorneringColour as CorneringColourReport,
		rep.AccelerationHighColour as AccelerationHighColourReport,
		rep.BrakingHighColour as BrakingHighColourReport,
		rep.CorneringHighColour as CorneringHighColourReport,
		rep.ManoeuvresLowColour as ManoeuvresLowColourReport,
		rep.ManoeuvresMedColour as ManoeuvresMedColourReport,
		rep.EngineServiceBrakeColour AS EngineServiceBrakeColourReport,
		rep.OverRevWithoutFuelColour AS OverRevWithoutFuelColourReport,
		rep.CoastOutOfGearColour AS CoastOutOfGearColourReport,
		rep.OverRevCountColour AS OverRevCountColourReport,
		
    rep.OverspeedCountColour AS OverspeedCountColourReport,
    rep.OverspeedHighCountColour AS OverspeedHighCountColourReport,
    rep.StabilityControlColour AS StabilityControlColourReport,
    rep.CollisionWarningLowColour AS CollisionWarningLowColourReport,
    rep.CollisionWarningMedColour AS CollisionWarningMedColourReport,
    rep.CollisionWarningHighColour AS CollisionWarningHighColourReport,
    rep.LaneDepartureDisableColour AS LaneDepartureDisableColourReport,
    rep.LaneDepartureLeftRightColour AS LaneDepartureLeftRightColourReport,
    rep.FatigueColour AS FatigueColourReport,
    rep.DistractionColour AS DistractionColourReport,
    rep.SweetSpotTimeColour AS SweetSpotTimeColourReport, 
    rep.OverRevTimeColour AS OverRevTimeColourReport,
    rep.TopGearTimeColour AS TopGearTimeColourReport,

		@scoreRounding AS ScoreRounding,
		@abcRounding AS ABCRounding
	
	FROM @ResultSet r1
	INNER JOIN @ResultSet ent ON r1.GroupId = ent.GroupId --AND ent.VehicleId IS NULL
	INNER JOIN @ResultSet rep ON rep.GroupId IS NULL --AND rep.VehicleId IS NULL
	WHERE r1.GroupId IS NOT NULL
	ORDER BY ent.Safety DESC





GO
