SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[proc_BulkInsertRTIME]
AS

--ALTER TABLE RTIME NOCHECK CONSTRAINT ALL

INSERT INTO RTIME SELECT * FROM RTIMETemp WHERE Archived = 0

--ALTER TABLE RTIME CHECK CONSTRAINT ALL

GO
