CREATE TABLE [dbo].[Diagnostics]
(
[DiagnosticsId] [int] NOT NULL IDENTITY(1, 1),
[UserId] [uniqueidentifier] NULL,
[Date] [datetime] NULL,
[VehicleId] [uniqueidentifier] NULL,
[IVHId] [uniqueidentifier] NULL,
[CompletedDateTime] [datetime] NULL,
[IgnitionDateTime] [datetime] NULL,
[LastEventDateTime] [datetime] NULL,
[TotalDistance] [float] NULL,
[AverageRPM] [float] NULL,
[TotalFuel] [float] NULL,
[DrivingFuel] [float] NULL,
[ShortIdleFuel] [float] NULL,
[GPSSatelliteCount] [int] NULL,
[DriverNumber] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sensor0] [int] NULL,
[Sensor0Max] [float] NULL,
[Sensor0Min] [float] NULL,
[Sensor0Current] [float] NULL,
[Sensor1] [int] NULL,
[Sensor1Max] [float] NULL,
[Sensor1Min] [float] NULL,
[Sensor1Current] [float] NULL,
[Sensor2] [int] NULL,
[Sensor2Max] [float] NULL,
[Sensor2Min] [float] NULL,
[Sensor2Current] [float] NULL,
[Sensor3] [int] NULL,
[Sensor3Max] [float] NULL,
[Sensor3Min] [float] NULL,
[Sensor3Current] [float] NULL,
[DigitalIO1] [int] NULL,
[DigitalIO2] [int] NULL,
[DigitalIO3] [int] NULL,
[DigitalIO4] [int] NULL,
[CustomerName] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VehicleGroups] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Version] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Website] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Network] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Com1] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Com2] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CanType] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Options] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SensorConfig] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Registration] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackerNumber] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalIdleTime] [float] NULL,
[AccumStart] [datetime] NULL,
[AccumEnd] [datetime] NULL,
[CameraID] [uniqueidentifier] NULL,
[CameraSerial] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastCameraEventDateTime] [datetime] NULL,
[CameraState] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CameraFirmware] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CameraVideoId] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CameraVideoType] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CameraVideoState] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccumCount] [int] NULL,
[HardwareStatus] [int] NULL,
[DIG_DigidownTConnected] [bit] NULL,
[DIG_TachographConnected] [bit] NULL,
[MakeModel] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BodyManufacturer] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BodyType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChassisNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Odometer] [float] NULL,
[Comment] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CameraSIMICCID] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CameraSIMDataUsage] [float] NULL,
[CameraSIMRatePlan] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CameraSIMStatus] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CameraSIMLimitReached] [bit] NULL,
[CameraSIMLastSession] [datetime] NULL,
[PulsFirstId] [datetime] NULL,
[PulsLastId] [datetime] NULL,
[PulsLastConfigUpdate] [datetime] NULL,
[PulsConfigStatus] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PulsConfigGroup] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobReference] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobType] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Diagnostics] ADD CONSTRAINT [PK_Diagnostics] PRIMARY KEY CLUSTERED  ([DiagnosticsId]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
