CREATE TABLE [dbo].[Maintenance]
(
[MaintenanceId] [bigint] NOT NULL IDENTITY(1, 1),
[CustomerIntId] [int] NOT NULL,
[VehicleIntId] [int] NOT NULL,
[Date] [datetime] NOT NULL,
[IVHIntId] [int] NULL,
[SS1] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SWS] [int] NULL,
[BatteryDisconnect] [int] NULL,
[HardwareErrors] [int] NULL,
[GPRSRetries] [int] NULL,
[TXFails] [int] NULL,
[TANCheckout] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DaysSincePoll] [int] NULL,
[DaysSinceDrive] [int] NULL,
[GPSDriveDistance] [float] NULL,
[CANDriveDistance] [float] NULL,
[CANDriveDistanceNoID] [float] NULL,
[T0] [bit] NULL,
[T1] [bit] NULL,
[T2] [bit] NULL,
[T3] [bit] NULL,
[DID1] [bit] NULL,
[DID2] [bit] NULL,
[CAN] [bit] NULL,
[GPS] [bit] NULL,
[GPSDrift] [bit] NULL,
[MaxDataAgeMins] [int] NULL,
[MinBatteryCharge] [smallint] NULL,
[MaxBatteryCharge] [smallint] NULL,
[AvgBatteryCharge] [smallint] NULL,
[MinExternalVoltage] [smallint] NULL,
[MaxExternalVoltage] [smallint] NULL,
[AvgExternalVoltage] [smallint] NULL,
[Acceleration] [int] NULL,
[Braking] [int] NULL,
[Cornering] [int] NULL,
[Accelerometer] [bit] NULL,
[Ignition] [bit] NULL,
[DrivingFuel] [float] NULL,
[iButton] [bit] NULL,
[Tacho] [bit] NULL,
[CheetahFaults] [int] NULL,
[SS1Faults] [int] NULL,
[Sensor01] [bit] NULL,
[Sensor02] [bit] NULL,
[Sensor03] [bit] NULL,
[Sensor04] [bit] NULL,
[DriverIdInUse] [bit] NULL,
[AverageRPM] [smallint] NULL,
[ConsumedFuel] [float] NULL,
[BelowSweetSpotDistance] [float] NULL,
[BelowSweetSpotFuel] [float] NULL,
[SweetSpotDistance] [float] NULL,
[SweetSpotFuel] [float] NULL,
[OverRevDistance] [float] NULL,
[OverRevFuel] [float] NULL,
[Camera] [bit] NULL,
[Video] [bit] NULL,
[Corruption] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Maintenance] ADD CONSTRAINT [PK_Maintenance] PRIMARY KEY CLUSTERED  ([MaintenanceId]) WITH (FILLFACTOR=80, IGNORE_DUP_KEY=ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Maintenance_DateVehicle] ON [dbo].[Maintenance] ([Date], [VehicleIntId]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Maintenance_VehicleDate] ON [dbo].[Maintenance] ([VehicleIntId], [Date]) ON [PRIMARY]
GO
