CREATE TABLE [dbo].[CAM_Coaching]
(
[CoachingId] [int] NOT NULL IDENTITY(1, 1),
[CoachingSessionId] [int] NOT NULL,
[PeriodNum] [int] NULL,
[PeriodStartDate] [datetime] NULL,
[PeriodEndDate] [datetime] NULL,
[VehicleId] [uniqueidentifier] NULL,
[DriverId] [uniqueidentifier] NULL,
[Safety] [float] NULL,
[Efficiency] [float] NULL,
[FuelEcon] [float] NULL,
[TotalDrivingDistance] [float] NULL,
[TotalTime] [float] NULL,
[Coached] [int] NULL,
[NotRequired] [int] NULL,
[NotCoached] [int] NULL,
[EngineServiceBrake] [float] NULL,
[OverRevWithoutFuel] [float] NULL,
[OverSpeed] [float] NULL,
[OverSpeedHigh] [float] NULL,
[IVHOverSpeed] [float] NULL,
[CoastOutOfGear] [float] NULL,
[HarshBraking] [float] NULL,
[Rop] [float] NULL,
[Rop2] [float] NULL,
[Acceleration] [float] NULL,
[Braking] [float] NULL,
[Cornering] [float] NULL,
[ManoeuvresLow] [float] NULL,
[ManoeuvresMed] [float] NULL,
[AccelerationHigh] [float] NULL,
[BrakingHigh] [float] NULL,
[CorneringHigh] [float] NULL,
[OverRevCount] [float] NULL,
[SweetSpot] [float] NULL,
[OverRevWithFuel] [float] NULL,
[TopGear] [float] NULL,
[Cruise] [float] NULL,
[CruiseInTopGears] [float] NULL,
[CruiseTopGearRatio] [float] NULL,
[CoastInGear] [float] NULL,
[Idle] [float] NULL,
[Co2] [float] NULL,
[Pto] [float] NULL,
[SweetSpotComponent] [float] NULL,
[OverRevWithFuelComponent] [float] NULL,
[TopGearComponent] [float] NULL,
[CruiseComponent] [float] NULL,
[CruiseInTopGearsComponent] [float] NULL,
[CruiseTopGearRatioComponent] [float] NULL,
[IdleComponent] [float] NULL,
[EngineServiceBrakeComponent] [float] NULL,
[OverRevWithoutFuelComponent] [float] NULL,
[RopComponent] [float] NULL,
[Rop2Component] [float] NULL,
[OverSpeedComponent] [float] NULL,
[OverSpeedHighComponent] [float] NULL,
[OverSpeedDistanceComponent] [float] NULL,
[IVHOverSpeedComponent] [float] NULL,
[CoastOutOfGearComponent] [float] NULL,
[CoastInGearComponent] [float] NULL,
[HarshBrakingComponent] [float] NULL,
[AccelerationComponent] [float] NULL,
[BrakingComponent] [float] NULL,
[CorneringComponent] [float] NULL,
[AccelerationLowComponent] [float] NULL,
[BrakingLowComponent] [float] NULL,
[CorneringLowComponent] [float] NULL,
[AccelerationHighComponent] [float] NULL,
[BrakingHighComponent] [float] NULL,
[CorneringHighComponent] [float] NULL,
[ManoeuvresLowComponent] [float] NULL,
[ManoeuvresMedComponent] [float] NULL,
[FuelMult] [float] NULL,
[CreationDateTime] [datetime] NULL,
[ClosureDateTime] [datetime] NULL,
[SweetSpotColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SweetSpotMix] [smallint] NULL,
[OverRevWithFuelColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverRevWithFuelMix] [smallint] NULL,
[TopGearColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TopGearMix] [smallint] NULL,
[CruiseColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CruiseMix] [smallint] NULL,
[CruiseInTopGearsColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CruiseInTopGearsMix] [smallint] NULL,
[CoastInGearColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoastInGearMix] [smallint] NULL,
[IdleColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IdleMix] [smallint] NULL,
[EngineServiceBrakeColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EngineServiceBrakeMix] [smallint] NULL,
[OverRevWithoutFuelColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverRevWithoutFuelMix] [smallint] NULL,
[RopColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RopMix] [smallint] NULL,
[Rop2Colour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rop2Mix] [smallint] NULL,
[OverSpeedColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverSpeedMix] [smallint] NULL,
[OverSpeedHighColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverSpeedHighMix] [smallint] NULL,
[IVHOverSpeedColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IVHOverSpeedMix] [smallint] NULL,
[CoastOutOfGearColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoastOutOfGearMix] [smallint] NULL,
[HarshBrakingColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HarshBrakingMix] [smallint] NULL,
[EfficiencyColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EfficiencyMix] [smallint] NULL,
[SafetyColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SafetyMix] [smallint] NULL,
[KPLColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KPLMix] [smallint] NULL,
[Co2Colour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Co2Mix] [smallint] NULL,
[OverSpeedDistanceColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverSpeedDistanceMix] [smallint] NULL,
[AccelerationColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccelerationMix] [smallint] NULL,
[BrakingColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BrakingMix] [smallint] NULL,
[CorneringColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CorneringMix] [smallint] NULL,
[AccelerationLowColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccelerationLowMix] [smallint] NULL,
[BrakingLowColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BrakingLowMix] [smallint] NULL,
[CorneringLowColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CorneringLowMix] [smallint] NULL,
[AccelerationHighColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccelerationHighMix] [smallint] NULL,
[BrakingHighColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BrakingHighMix] [smallint] NULL,
[CorneringHighColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CorneringHighMix] [smallint] NULL,
[ManoeuvresLowColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ManoeuvresLowMix] [smallint] NULL,
[ManoeuvresMedColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ManoeuvresMedMix] [smallint] NULL,
[CruiseTopGearRatioColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CruiseTopGearRatioMix] [smallint] NULL,
[OverRevCountColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverRevCountMix] [smallint] NULL,
[PtoColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PtoMix] [smallint] NULL,
[CruiseOverspeed] [float] NULL,
[CruiseOverspeedComponent] [float] NULL,
[CruiseOverspeedColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CruiseOverspeedMix] [smallint] NULL,
[TopGearOverspeed] [float] NULL,
[TopGearOverspeedComponent] [float] NULL,
[TopGearOverspeedColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TopGearOverspeedMix] [smallint] NULL,
[FuelWastageCost] [float] NULL,
[FuelWastageCostColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverspeedCount] [float] NULL,
[OverspeedHighCount] [float] NULL,
[StabilityControl] [float] NULL,
[CollisionWarningLow] [float] NULL,
[CollisionWarningMed] [float] NULL,
[CollisionWarningHigh] [float] NULL,
[LaneDepartureDisable] [float] NULL,
[LaneDepartureLeftRight] [float] NULL,
[SweetSpotTime] [float] NULL,
[OverRevTime] [float] NULL,
[TopGearTime] [float] NULL,
[Fatigue] [float] NULL,
[Distraction] [float] NULL,
[OverspeedCountComponent] [float] NULL,
[OverspeedHighCountComponent] [float] NULL,
[StabilityControlComponent] [float] NULL,
[CollisionWarningLowComponent] [float] NULL,
[CollisionWarningMedComponent] [float] NULL,
[CollisionWarningHighComponent] [float] NULL,
[LaneDepartureDisableComponent] [float] NULL,
[LaneDepartureLeftRightComponent] [float] NULL,
[SweetSpotTimeComponent] [float] NULL,
[OverRevTimeComponent] [float] NULL,
[TopGearTimeComponent] [float] NULL,
[FatigueComponent] [float] NULL,
[DistractionComponent] [float] NULL,
[OverspeedCountColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverspeedCountMix] [tinyint] NULL,
[OverspeedHighCountColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverspeedHighCountMix] [tinyint] NULL,
[StabilityControlColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StabilityControlMix] [tinyint] NULL,
[CollisionWarningLowColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollisionWarningLowMix] [tinyint] NULL,
[CollisionWarningMedColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollisionWarningMedMix] [tinyint] NULL,
[CollisionWarningHighColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollisionWarningHighMix] [tinyint] NULL,
[LaneDepartureDisableColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LaneDepartureDisableMix] [tinyint] NULL,
[LaneDepartureLeftRightColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LaneDepartureLeftRightMix] [tinyint] NULL,
[SweetSpotTimeColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SweetSpotTimeMix] [tinyint] NULL,
[OverRevTimeColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverRevTimeMix] [tinyint] NULL,
[TopGearTimeColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TopGearTimeMix] [tinyint] NULL,
[FatigueColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FatigueMix] [tinyint] NULL,
[DistractionColour] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DistractionMix] [tinyint] NULL,
[SpeedGauge] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpeedGaugeComponent] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpeedGaugeColour] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpeedGaugeMix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CAM_Coaching] ADD CONSTRAINT [PK_CAM_Coachingn] PRIMARY KEY CLUSTERED  ([CoachingId]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CAM_Coaching] ADD CONSTRAINT [FK_CAM_Coaching_CAM_CoachingSession] FOREIGN KEY ([CoachingSessionId]) REFERENCES [dbo].[CAM_CoachingSession] ([CoachingSessionId])
GO
