CREATE TABLE [dbo].[LoadTemp]
(
[LoadId] [bigint] NOT NULL IDENTITY(1, 1),
[CreationCodeId] [smallint] NOT NULL,
[CreationDateTime] [datetime] NOT NULL,
[ClosureCodeId] [smallint] NOT NULL,
[ClosureDateTime] [datetime] NOT NULL,
[ClosureLat] [float] NOT NULL,
[ClosureLong] [float] NOT NULL,
[VehicleIntId] [int] NOT NULL,
[DriverIntId] [int] NOT NULL,
[CustomerIntId] [int] NOT NULL,
[TotalTime] [int] NOT NULL,
[TotalDistance] [float] NOT NULL,
[TotalFuel] [float] NOT NULL,
[TotalTime100] [int] NOT NULL,
[TotalDistance100] [float] NOT NULL,
[TotalFuel100] [float] NOT NULL,
[TotalTime0] [int] NOT NULL,
[TotalDistance0] [float] NOT NULL,
[TotalFuel0] [float] NOT NULL,
[TotalTime0_13] [int] NOT NULL,
[TotalDistance0_13] [float] NOT NULL,
[TotalFuel0_13] [float] NOT NULL,
[TotalTime14_37] [int] NOT NULL,
[TotalDistance14_37] [float] NOT NULL,
[TotalFuel14_37] [float] NOT NULL,
[TotalTime38_63] [int] NOT NULL,
[TotalDistance38_63] [float] NOT NULL,
[TotalFuel38_63] [float] NOT NULL,
[TotalTime64_88] [int] NOT NULL,
[TotalDistance64_88] [float] NOT NULL,
[TotalFuel64_88] [float] NOT NULL,
[TotalTime89_99] [int] NOT NULL,
[TotalDistance89_99] [float] NOT NULL,
[TotalFuel89_99] [float] NOT NULL,
[LastOperation] [smalldatetime] NOT NULL CONSTRAINT [DF_LoadTemp_LastOperation] DEFAULT (getutcdate()),
[Archived] [bit] NOT NULL
) ON [PRIMARY]
GO
